
-- Create schema and base tables.
CREATE SCHEMA "MYGRAPH";

CREATE COLUMN TABLE "MYGRAPH"."CUSTOMERMASTER" (
  "USERID"   VARCHAR(100) PRIMARY KEY,
	"NAME" VARCHAR(100) ,
	"COUNTRY" VARCHAR(100)
);

CREATE COLUMN TABLE "MYGRAPH"."PRODUCTMASTER" (
  "PRODUCTID"   VARCHAR(100) PRIMARY KEY,
	"DESCRIPTION" VARCHAR(100) ,
	"COUNTRY" VARCHAR(100)
);

CREATE COLUMN TABLE "MYGRAPH"."ORDERS" (
  "USERID"   VARCHAR(100) ,
	"PRODUCTID" VARCHAR(100),
	"QUANTITY" VARCHAR(100)
);

